spring:
  datasource:
    username: root
    password: 8888
    url: jdbc:mysql://localhost:3306/localdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9191
